#CLIENTES
SELECT 
c.ID,
p.NOME,
p.APELIDO,
p.NOMEMAE,
p.NOMEPAI,
p.PONTODEREFERENCIA ,
p.TELEFONE1,
p.TELEFONE2,
p.TELEFONE3,
p.TELEFONE4,
p.DOC1 as cpf,
p.DOC2 as rg,
p.TIPO as TIPO_PESSOA,
c.CONTRATO ,
c.COMPLEMENTO,
c.DATACADASTRO,
c.NUMEROCOBRANCA,
ed.BAIRRO,
ed.CIDADE,
ed.CEP,
ed.RUA,
ed.UF,
s2.DESCRICAO as nome_plano,
s2.DOWNLOAD,
s2.UPLOAD,
s2.VALOR,
a.USUARIO,
a.SENHA,
a.MAC,
a.IPFIXO 
FROM LHISP.CLIENTE c INNER JOIN LHISP.ENDERECO ed ON (c.ENDERECO_ID = ed.ID)
INNER JOIN LHISP.PESSOA p ON (c.PESSOA_ID = p.ID)
INNER JOIN LHISP.SERVICOCONTRATADO s ON (c.ID = s.CLIENTE_ID)
INNER JOIN LHISP.SERVICO s2 ON (s.SERVICO_ID = s2.ID)
INNER JOIN LHISP.ACESSO a on (s.ID = a.SERVICO_ID);

#PORTADORES
SELECT 
t.ID,
t.CARTEIRA, 
t.BANCO,
t.CODIGOBANCO,
t.DESCRICAO
FROM LHISP.TIPOCOBRANCA t;

#TITULOS
SELECT  
c.ID,
c.CLIENTE_ID,
c.SERVICO_ID,
c.VENCIMENTO,
c.VALOR,
c.VALORPAGO,
c.LINHADIGITAVEL,
c.CODIGODEBARRAS,
c.DATACANCELAMENTO,
c.DATAPAGAMENTO,
c.DATABAIXA,
c.DATAGERACAO,
c.BOLETOURL,
c.CARNEURL,
cb.COBRANCA_ID as id_gateway,
c.NRDOC as NUMERO_DOCUMENTO
FROM  LHISP.CONTARECEBER c INNER JOIN LHISP.CONTABANCARIA cb on (c.CONTABANCARIA_ID=cb.ID);

#EMPRESA
SELECT 
e.ID,
e.CONTRATACAO,
e.CNPJ,
e.NOME,
e.RAZAOSOCIAL
FROM LHISP.EMPRESA e;


#NOTA FISCAL
SELECT 
n.ID ,
n.EMPRESA_ID,
n.tipo,
n.CNPJ,
n.DOC1,
n.SERIE,
n.VALOR,
n.NRSERIE,
n.PESSOA_ID,
n.MODELO,
n.BASECALCULO,
n.ALIQUOTA,
n.CFOP,
n.MES,
n.ANO,
n.SITUACAO,
n.NRDOC,
n.VENCIMENTO,
n.RAZAOSOCIAL,
n.INSCRICAOESTADUAL,
n.TOTAL_SCM,
n.TOTAL_OUTROS
FROM LHISP.NOTAFISCAL n INNER JOIN LHISP.EMPRESA e on (n.EMPRESA_ID = e.ID);



#NOTA FISCAL ITEM
SELECT ni.NOTAFISCAL_ID, ni.DESCRICAO, ni.VALOR FROM LHISP.NOTAFISCAL_ITENS ni;

