select c.id,
       r.username as login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        c.endereco,c.numero,c.complemento,
        c.bairro,c.cep,c.estado,c.cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        c.plano,
        '0' as valor,
        c.tipo,
        c.ip,
        c.ip,
        c.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        c.bloqueado,
        r.value as senha,
        p.veldown as plano_download,
        p.velup as plano_upload,
        p.valor as plano_valor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade
from sis_cliente c 
INNER JOIN sis_plano p on (p.nome=c.plano)
INNER JOIN radcheck r ON (r.login=c.login and r.attribute='Password' and r.login not like '%:%')
WHERE c.cli_ativado = 's' and STR_TO_DATE(cadastro,'%e/%m/%Y') > '2022-10-05'
INTO OUTFILE '/tmp/mkauth-clientes-ativados.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';

select c.id,
       c.login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        c.endereco,c.numero,c.complemento,
        c.bairro,c.cep,c.estado,c.cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        c.plano,
        '0' as valor,
        c.tipo,
        c.ip,
        c.ip,
        c.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        c.bloqueado,
        c.senha,
        p.veldown as plano_download,
        p.velup as plano_upload,
        p.valor as plano_valor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade
from sis_cliente c 
INNER JOIN sis_plano p on (p.nome=c.plano)
WHERE c.cli_ativado = 's'  and STR_TO_DATE(cadastro,'%e/%m/%Y') > '2022-10-05'
INTO OUTFILE '/tmp/mkauth-clientes-ativados2.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';

select c.id,
       c.login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        c.endereco,c.numero,c.complemento,
        c.bairro,c.cep,c.estado,c.cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        (select groupname from radusergroup where username=c.login limit 1) as plano,
        '0' as valor,
        c.tipo,
        c.ip,
        c.ip,
        c.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        c.bloqueado,
        c.senha,
        10240 as download,
        10240 as upload,
        0 as planovalor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade
from sis_cliente c 
LEFT JOIN sis_plano p on (p.nome=c.plano)
WHERE c.cli_ativado = 's' and p.nome is null   and STR_TO_DATE(cadastro,'%e/%m/%Y') > '2022-10-05'
INTO OUTFILE '/tmp/mkauth-clientes-ativados3.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';





select c.id,
       c.login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        c.endereco,c.numero,c.complemento,
        c.bairro,c.cep,c.estado,c.cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        IFNULL(c.plano,'PLANO_DESATIVADO') as plano,
        '0' as valor,
        c.tipo,
        c.ip,
        c.ip,
        c.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        c.bloqueado,
        c.senha,
        IFNULL(p.veldown,'0') as plano_download,
        IFNULL(p.velup,'0') as plano_upload,
        IFNULL(p.valor,'0') as plano_valor,
        '0' as conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade
from sis_cliente c 
LEFT JOIN sis_plano p on (p.nome=c.plano)
WHERE c.cli_ativado = 'n' and STR_TO_DATE(cadastro,'%e/%m/%Y') > '2022-10-05'
INTO OUTFILE '/tmp/mkauth-clientes-desativados.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';



select c.id,
       a.username as login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        IFNULL(a.end_endereco,c.endereco) as endereco,
        IFNULL(a.end_numero,c.numero) as numero,
        IFNULL(a.end_complemento,c.complemento) as complemento,
        IFNULL(a.end_bairro,c.bairro) as bairro,
        c.cep,c.estado,
        IFNULL(a.end_cidade,c.cidade) as cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        a.plano,
        '0' as valor,
        a.tipo,
        a.ip,
        a.ip,
        a.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        a.bloqueado,
        a.senha as senha,
        p.veldown as plano_download,
        p.velup as plano_upload,
        p.valor as plano_valor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade
from sis_cliente c 
INNER JOIN sis_adicional a ON (a.login=c.login)
INNER JOIN sis_plano p on (p.nome=a.plano)
WHERE c.cli_ativado = 's'  and STR_TO_DATE(cadastro,'%e/%m/%Y') > '2022-10-05'
INTO OUTFILE '/tmp/mkauth-clientes-adicional.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';


select c.id,
       a.username as login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        IFNULL(a.end_endereco,c.endereco) as endereco,
        IFNULL(a.end_numero,c.numero) as numero,
        IFNULL(a.end_complemento,c.complemento) as complemento,
        IFNULL(a.end_bairro,c.bairro) as bairro,
        c.cep,c.estado,
        IFNULL(a.end_cidade,c.cidade) as cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        (select groupname from radusergroup where username=a.username limit 1) as plano,
        '0' as valor,
        a.tipo,
        a.ip,
        a.ip,
        a.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        a.bloqueado,
        a.senha as senha,
        IFNULL(p.veldown,'0') as plano_download,
        IFNULL(p.velup,'0') as plano_upload,
        IFNULL(p.valor,'0') as plano_valor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade
from sis_cliente c 
INNER JOIN sis_adicional a ON (a.login=c.login)
LEFT JOIN sis_plano p on (p.nome=a.plano)
WHERE c.cli_ativado = 's' and p.nome is null and STR_TO_DATE(cadastro,'%e/%m/%Y') > '2022-10-05'
INTO OUTFILE '/tmp/mkauth-clientes-adicional2.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';