select c.id,
       r.username as login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        c.endereco,c.numero,c.complemento,
        c.bairro,c.cep,c.estado,c.cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        c.plano,
        '0' as valor,
        c.tipo,
        c.ip,
        c.ip,
        c.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        c.bloqueado,
        r.value as senha,
        p.veldown as plano_download,
        p.velup as plano_upload,
        p.valor as plano_valor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade,
        c.dot_ref as ponto_referencia
from sis_cliente c 
INNER JOIN sis_plano p on (p.nome=c.plano)
INNER JOIN radcheck r ON (r.login=c.login and r.attribute='Password' and r.login not like '%:%')
WHERE c.cli_ativado = 's'
INTO OUTFILE '/tmp/mkauth-clientes-ativados.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';

select c.id,
       c.login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        c.endereco,c.numero,c.complemento,
        c.bairro,c.cep,c.estado,c.cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        c.plano,
        '0' as valor,
        c.tipo,
        c.ip,
        c.ip,
        c.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        c.bloqueado,
        c.senha,
        p.veldown as plano_download,
        p.velup as plano_upload,
        p.valor as plano_valor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade,
        c.dot_ref as ponto_referencia
from sis_cliente c 
INNER JOIN sis_plano p on (p.nome=c.plano)
WHERE c.cli_ativado = 's'
INTO OUTFILE '/tmp/mkauth-clientes-ativados2.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';

select c.id,
       c.login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        c.endereco,c.numero,c.complemento,
        c.bairro,c.cep,c.estado,c.cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        (select groupname from radusergroup where username=c.login limit 1) as plano,
        '0' as valor,
        c.tipo,
        c.ip,
        c.ip,
        c.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        c.bloqueado,
        c.senha,
        10240 as download,
        10240 as upload,
        0 as planovalor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade,
        c.dot_ref as ponto_referencia
from sis_cliente c 
LEFT JOIN sis_plano p on (p.nome=c.plano)
WHERE c.cli_ativado = 's' and p.nome is null 
INTO OUTFILE '/tmp/mkauth-clientes-ativados3.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';

select login,coordenadas from sis_cliente where coordenadas is not null
INTO OUTFILE '/tmp/mkauth-clientes-coordenadas.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';



select c.id,
       c.login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        c.endereco,c.numero,c.complemento,
        c.bairro,c.cep,c.estado,c.cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        IFNULL(c.plano,'PLANO_DESATIVADO') as plano,
        '0' as valor,
        c.tipo,
        c.ip,
        c.ip,
        c.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        c.bloqueado,
        c.senha,
        IFNULL(p.veldown,'0') as plano_download,
        IFNULL(p.velup,'0') as plano_upload,
        IFNULL(p.valor,'0') as plano_valor,
        '0' as conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade,
        c.dot_ref as ponto_referencia
from sis_cliente c 
LEFT JOIN sis_plano p on (p.nome=c.plano)
WHERE c.cli_ativado = 'n'
INTO OUTFILE '/tmp/mkauth-clientes-desativados.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';

select c.id,
       a.username as login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        IFNULL(a.end_endereco,c.endereco) as endereco,
        IFNULL(a.end_numero,c.numero) as numero,
        IFNULL(a.end_complemento,c.complemento) as complemento,
        IFNULL(a.end_bairro,c.bairro) as bairro,
        c.cep,c.estado,
        IFNULL(a.end_cidade,c.cidade) as cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        a.plano,
        '0' as valor,
        a.tipo,
        a.ip,
        a.ip,
        a.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        a.bloqueado,
        a.senha as senha,
        p.veldown as plano_download,
        p.velup as plano_upload,
        p.valor as plano_valor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade,
        c.dot_ref as ponto_referencia
from sis_cliente c 
INNER JOIN sis_adicional a ON (a.login=c.login)
INNER JOIN sis_plano p on (p.nome=a.plano)
WHERE c.cli_ativado = 's'
INTO OUTFILE '/tmp/mkauth-clientes-adicional.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';


select c.id,
       a.username as login,
       c.pessoa,
       c.nome,
       1,
       c.cpf_cnpj,
       10,
       15,
       rg,
       '' as profissao,
       '' as sexo,
       c.nascimento,
       '' as fantasia, 
       '' as contato, 
        IFNULL(a.end_endereco,c.endereco) as endereco,
        IFNULL(a.end_numero,c.numero) as numero,
        IFNULL(a.end_complemento,c.complemento) as complemento,
        IFNULL(a.end_bairro,c.bairro) as bairro,
        c.cep,c.estado,
        IFNULL(a.end_cidade,c.cidade) as cidade,
        c.celular,c.celular2,c.email,c.obs,c.cadastro,c.cadastro,
        '' as servidor,
        (select groupname from radusergroup where username=a.username limit 1) as plano,
        '0' as valor,
        a.tipo,
        a.ip,
        a.ip,
        a.mac,
        c.venc,
        c.desconto,
        c.acrescimo,
        '' as transmissor,
        '' as receptor,
        c.comodato,
        c.isento,
        c.cli_ativado,
        a.bloqueado,
        a.senha as senha,
        IFNULL(p.veldown,'0') as plano_download,
        IFNULL(p.velup,'0') as plano_upload,
        IFNULL(p.valor,'0') as plano_valor,
        c.conta,
        c.fone,
        c.login,
        c.endereco_res,
        c.numero_res,
        c.bairro_res,
        c.cidade_res,
        c.cep_res,
        c.estado_res,
        c.complemento_res,
        c.nome_pai,
        c.nome_mae,
        c.naturalidade,
        c.dot_ref as ponto_referencia
from sis_cliente c 
INNER JOIN sis_adicional a ON (a.login=c.login)
LEFT JOIN sis_plano p on (p.nome=a.plano)
WHERE c.cli_ativado = 's' and p.nome is null
INTO OUTFILE '/tmp/mkauth-clientes-adicional2.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';


select
chamado,
login,
CONCAT("MKAUTH ",assunto) as assunto,
status,
abertura,
visita,
fechamento,
CONCAT("Motivo:", assunto, "\nAtendente:",atendente) as conteudo,
motivo_fechar as servicoprestado
from sis_suporte
INTO OUTFILE '/tmp/mkauth-chamados.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';


DROP VIEW IF EXISTS vtab_titulos ;
CREATE  VIEW vtab_titulos AS
    SELECT sis_cliente.nome, sis_cliente.pessoa, sis_cliente.nome_res, sis_cliente.senha, sis_cliente.email, sis_cliente.vendedor, sis_cliente.endereco, sis_cliente.complemento, sis_cliente.bairro, sis_cliente.cidade, sis_cliente.cep, sis_cliente.estado, sis_cliente.cpf_cnpj, sis_cliente.fone, sis_cliente.login, sis_cliente.venc, sis_cliente.celular, sis_cliente.conta, sis_cliente.plano, sis_cliente.numero, sis_cliente.desconto, sis_cliente.acrescimo, sis_cliente.ramal, sis_cliente.cli_ativado, sis_cliente.bloqueado, sis_cliente.grupo, sis_cliente.codigo, ((REPLACE(sis_lanc.valor, ',', '.') - sis_cliente.desconto) + sis_cliente.acrescimo) AS calculado, sis_cliente.tags, sis_cliente.comodato, sis_cliente.dias_corte, sis_cliente.geranfe, sis_cliente.mesref, REPLACE(sis_lanc.valor, ',', '.') AS valor, REPLACE(sis_lanc.valorpag, ',', '.') AS valorpag, sis_lanc.valorger, sis_lanc.formapag, sis_lanc.linhadig, '', sis_lanc.id AS titulo, sis_lanc.datavenc, sis_lanc.referencia, sis_lanc.nossonum, sis_lanc.datapag, sis_lanc.recibo,  sis_lanc.status, sis_lanc.tipo, sis_lanc.processamento, sis_lanc.usergerou, sis_lanc.coletor, sis_lanc.tipocob, sis_lanc.codigo_carne, sis_lanc.fcartaobandeira, sis_lanc.fcartaonumero, sis_lanc.fchequenumero, sis_lanc.fchequebanco, sis_lanc.fchequeagcc, sis_lanc.obs AS descricao, sis_lanc.numconta, ''as retorno, sis_lanc.deltitulo, sis_lanc.gerourem
    FROM sis_cliente,  sis_lanc
    WHERE  sis_cliente.login = sis_lanc.login;


select id,nome from sis_boleto; 

select chamado,atendente, msg_data, msg from sis_msg INTO OUTFILE '/tmp/mkauth-msg-ocorrencia.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';



select chamado, motivo_fechar, data from sis_suporte INTO OUTFILE '/tmp/mkauth-motivo-fechamento-ocorrencia.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
